package normalize

var metroCities = map[string]string{
	"rio de janeiro":        "RJ",
	"niteroi":               "RJ",
	"sao goncalo":           "RJ",
	"duque de caxias":       "RJ",
	"nova iguacu":           "RJ",
	"nilopolis":             "RJ",
	"sao joao de meriti":    "RJ",
	"belford roxo":          "RJ",
	"mage":                  "RJ",
	"itaborai":              "RJ",
	"marica":                "RJ",
	"queimados":             "RJ",
	"mesquita":              "RJ",
	"japeri":                "RJ",
	"seropedica":            "RJ",
	"itaguai":               "RJ",
	"guapimirim":            "RJ",
	"tangua":                "RJ",
	"paracambi":             "RJ",
	"rio bonito":            "RJ",
	"cachoeiras de macacu":  "RJ",
	"petropolis":            "RJ",
	"sao paulo":             "SP",
	"guarulhos":             "SP",
	"osasco":                "SP",
	"santo andre":           "SP",
	"sao bernardo do campo": "SP",
	"sao caetano do sul":    "SP",
	"diadema":               "SP",
	"maua":                  "SP",
	"ribeirao pires":        "SP",
	"barueri":               "SP",
	"carapicuiba":           "SP",
	"cotia":                 "SP",
	"taboao da serra":       "SP",
	"embu das artes":        "SP",
	"itapevi":               "SP",
	"jandira":               "SP",
	"santana de parnaiba":   "SP",
	"mogi das cruzes":       "SP",
	"suzano":                "SP",
	"itaquaquecetuba":       "SP",
	"ferraz de vasconcelos": "SP",
	"poa":                   "SP",
	"aruja":                 "SP",
	"caieiras":              "SP",
	"cajamar":               "SP",
	"franco da rocha":       "SP",
	"francisco morato":      "SP",
	"mairipora":             "SP",
	"itapecerica da serra":  "SP",
	"embu-guacu":            "SP",
	"curitiba":              "PR",
	"sao jose dos pinhais":  "PR",
	"pinhais":               "PR",
	"colombo":               "PR",
	"araucaria":             "PR",
	"campo largo":           "PR",
	"almirante tamandare":   "PR",
	"piraquara":             "PR",
	"fazenda rio grande":    "PR",
	"campina grande do sul": "PR",
	"quatro barras":         "PR",
	"rio branco do sul":     "PR",
	"mandirituba":           "PR",
	"contenda":              "PR",
	"balsa nova":            "PR",
	"lapa":                  "PR",
	"campo magro":           "PR",
	"itaperucu":             "PR",
}

var targetStates = map[string]bool{"RJ": true, "SP": true, "PR": true}
